import './styles.css';
import { api } from './services/api';

const state = { page: location.hash.slice(1) || 'overview', health: null, metrics: null, events: [], eventPage: null, parsers: [], sources: [], deadLetters: [], eventQuery: { page: 1, limit: 25, search: '' }, testResult: null, error: null };
const sampleLog = '<185>date=2026-09-09 time=14:02:11 devname="fw01" type=traffic level=notice srcip=10.0.0.5 srcport=54321 dstip=8.8.8.8 dstport=443 proto=6 action="deny" status=blocked msg="Access denied"';

function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
function statusClass(status) { return ({ PROCESSED: 'success', PARTIALLY_PROCESSED: 'warning', UNSUPPORTED: 'neutral', PARSER_ERROR: 'danger', VALIDATION_ERROR: 'danger', UP: 'success' }[status] || 'neutral'); }
function formatDate(value) { return value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'medium' }) : '-'; }
function valueAt(object, path) { return path.split('.').reduce((value, key) => value?.[key], object); }
function metric(label, value, note, tone = '') { return `<article class="metric ${tone}"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value ?? 0)}</strong><small>${escapeHtml(note)}</small></article>`; }
function badge(label, tone = 'neutral') { return `<span class="badge ${tone}">${escapeHtml(label)}</span>`; }
function pageLabel(page) { return ({ overview: 'Operations', pipeline: 'Operations', events: 'Operations', 'dead-letter': 'Operations', sources: 'Engineering', parsers: 'Engineering', test: 'Engineering', replay: 'Engineering', outputs: 'Delivery', analytics: 'Delivery', diagnostics: 'Delivery' }[page] || 'Operations'); }
function pageTitle(page) { return ({ overview: 'Platform overview', pipeline: 'Pipeline health', events: 'Event explorer', 'dead-letter': 'Quarantine', sources: 'Source registry', parsers: 'Parser registry', test: 'Parser test bench', replay: 'Replay center', outputs: 'Output delivery', analytics: 'Analytics', diagnostics: 'Diagnostics' }[page] || 'Platform overview'); }

function shell() {
  const nav = [['Operations', [['overview', 'Overview'], ['pipeline', 'Pipeline'], ['events', 'Event explorer'], ['dead-letter', 'Quarantine']]], ['Engineering', [['sources', 'Sources'], ['parsers', 'Parsers'], ['test', 'Parser test bench'], ['replay', 'Replay']]], ['Delivery', [['outputs', 'Outputs'], ['analytics', 'Analytics'], ['diagnostics', 'Diagnostics']]]];
  return `<div class="app-shell"><aside class="sidebar"><a class="product" href="#overview"><span class="product-mark">UL</span><span><strong>ULPF</strong><small>Universal Log Pre-processing Framework</small></span></a><div class="environment"><span class="live-dot"></span><span>LAB / INTERNAL</span><b>${state.health?.status || 'CHECKING'}</b></div><nav>${nav.map(([group, links]) => `<div class="nav-group"><small>${group}</small>${links.map(([id, label]) => `<a class="nav-link ${state.page === id ? 'active' : ''}" href="#${id}">${label}${id === 'dead-letter' && state.deadLetters.length ? `<b>${state.deadLetters.length}</b>` : ''}</a>`).join('')}</div>`).join('')}</nav><div class="sidebar-footer"><span class="status-dot"></span><span>API connected</span><small>Schema v1.0 / local state</small></div></aside><main class="workspace"><header class="topbar"><div><span class="breadcrumb">ULPF / ${escapeHtml(pageLabel(state.page))}</span><h1>${escapeHtml(pageTitle(state.page))}</h1></div><div class="topbar-tools"><label class="global-search"><span>⌕</span><input id="global-search" placeholder="Search events, sources, parsers" value="${escapeHtml(state.eventQuery.search)}" /></label><span class="runtime-chip">● ${escapeHtml(state.metrics?.events_per_second || 0)} EPS</span><button class="icon-button" id="refresh" title="Refresh data">↻</button></div></header><section id="content"></section></main></div><div id="toast" aria-live="polite"></div>`;
}

function render() { document.querySelector('#root').innerHTML = shell(); document.querySelector('#refresh').addEventListener('click', () => refresh(true)); document.querySelector('#global-search').addEventListener('keydown', event => { if (event.key === 'Enter') { state.eventQuery.search = event.currentTarget.value.trim(); state.eventQuery.page = 1; location.hash = '#events'; } }); renderPage(); }
function renderPage() { const content = document.querySelector('#content'); const route = state.page; const pages = { overview: overviewPage, pipeline: pipelinePage, events: eventsPage, 'dead-letter': deadLetterPage, sources: sourcesPage, parsers: parsersPage, test: testPage, replay: replayPage, outputs: outputsPage, analytics: analyticsPage, diagnostics: diagnosticsPage }; if (route.startsWith('event/')) { content.innerHTML = eventDetailPage(decodeURIComponent(route.slice(6))); bindEventDetail(); return; } content.innerHTML = (pages[route] || overviewPage)(); bindPage(route); }
function bindPage(route) { if (route === 'events') bindEvents(); if (route === 'sources') bindSources(); if (route === 'parsers') bindParsers(); if (route === 'test') bindTest(); if (route === 'replay') bindReplay(); if (route === 'outputs') bindOutputs(); }

async function refresh(showToast = false) { try { const [health, metrics, eventPage, parsers, sources, deadLetters] = await Promise.all([api.health(), api.metrics(), api.events({ page: state.eventQuery.page, limit: state.eventQuery.limit, ...(state.eventQuery.search ? { search: state.eventQuery.search } : {}) }), api.parsers(), api.sources(), api.deadLetters({ page: 1, limit: 5 })]); state.health = health; state.metrics = metrics; state.events = eventPage.events || []; state.eventPage = eventPage.pagination; state.parsers = parsers || []; state.sources = sources || []; state.deadLetters = deadLetters.events || []; state.error = null; render(); if (showToast) toast('Data refreshed from backend', 'success'); } catch (error) { state.error = error.message; render(); toast(error.message, 'danger'); } }

function overviewPage() { const counters = state.metrics?.counters || {}; const parserHits = Object.entries(state.metrics?.parser_hits || {}).sort((a, b) => b[1] - a[1]).slice(0, 5); return `<div class="page-intro"><div><span class="eyebrow">Operational command view</span><h2>One pipeline for every security log.</h2><p>ULPF preserves the original event, detects its format, normalizes it into a universal schema, and keeps the transformation explainable.</p></div><a class="button primary" href="#test">Ingest a test event <span>→</span></a></div>${state.error ? errorState(state.error) : ''}<section class="metric-strip">${metric('Events ingested', counters.eventsReceived, 'persisted raw inputs')}${metric('Events processed', counters.eventsProcessed, 'normalized events', 'success')}${metric('Events/sec', state.metrics?.events_per_second, 'current processing rate', 'info')}${metric('Dead letters', counters.eventsFailed, 'requires investigation', 'warning')}${metric('Active sources', state.sources.length, 'registered sources')}${metric('Active parsers', state.parsers.length, 'loaded definitions')}</section><div class="overview-grid"><section class="surface pipeline-summary"><div class="surface-header"><div><span class="eyebrow">Live processing path</span><h3>From raw input to delivery</h3></div><a href="#pipeline">Open pipeline →</a></div><div class="flow">${['Collectors', 'Raw store', 'Queue', 'Parser', 'Normalizer', 'Validator', 'Storage', 'Outputs'].map((stage, index) => `<div class="flow-stage"><span>${String(index + 1).padStart(2, '0')}</span><strong>${stage}</strong><small>${index < 2 ? 'available' : index === 7 ? 'export ready' : 'operational'}</small></div>`).join('<i>›</i>')}</div></section><section class="surface"><div class="surface-header"><div><span class="eyebrow">Format distribution</span><h3>Detected formats</h3></div></div>${distribution(state.metrics?.format_counts)}</section><section class="surface recent-events"><div class="surface-header"><div><span class="eyebrow">Investigation queue</span><h3>Latest normalized events</h3></div><a href="#events">View explorer →</a></div>${eventRows(state.events.slice(0, 5))}</section><section class="surface"><div class="surface-header"><div><span class="eyebrow">Parser health</span><h3>Most used definitions</h3></div><a href="#parsers">Registry →</a></div>${parserHits.length ? parserHits.map(([name, count]) => `<div class="rank-row"><span>${escapeHtml(name)}</span><b>${count}</b></div>`).join('') : emptyState('No parser activity yet.')}</section></div>`; }
function distribution(values = {}) { const entries = Object.entries(values).sort((a, b) => b[1] - a[1]); if (!entries.length) return emptyState('No format data available.'); const max = Math.max(entries[0][1], 1); return `<div class="distribution">${entries.map(([label, count]) => `<div class="distribution-row"><span>${escapeHtml(label)}</span><b>${count}</b><i style="width:${Math.max(4, count / max * 100)}%"></i></div>`).join('')}</div>`; }
function eventRows(events) { if (!events?.length) return `<div class="empty-state">No events stored yet.<small>Ingest a sample event to begin investigation.</small></div>`; return `<div class="event-list">${events.map(event => `<a class="event-row" href="#event/${encodeURIComponent(event.event_id)}"><span class="event-time">${escapeHtml(formatDate(event.raw_ref?.ingested_at))}</span><span><strong>${escapeHtml(event.event?.action || 'unclassified')}</strong><small>${escapeHtml(event.source?.vendor || 'Unknown')} · ${escapeHtml(event.source?.product || 'Unknown product')}</small></span><span class="event-network">${escapeHtml(event.network?.source_ip || '-')} <b>→</b> ${escapeHtml(event.network?.destination_ip || '-')}</span>${badge(event.processing?.status || 'UNKNOWN', statusClass(event.processing?.status))}</a>`).join('')}</div>`; }

function eventsPage() { const pagination = state.eventPage || { page: 1, total: 0, total_pages: 1, has_previous: false, has_next: false }; return `<div class="page-intro compact"><div><span class="eyebrow">Server-side investigation workspace</span><h2>Event explorer</h2><p>Search the persisted normalized event store without loading the full corpus into the browser.</p></div><a class="button primary" href="#test">Ingest event</a></div><section class="surface"><div class="filter-bar"><label class="search-field"><span>⌕</span><input id="event-search" value="${escapeHtml(state.eventQuery.search)}" placeholder="Search vendor, parser, action, IP, or event ID" /></label><button class="button secondary" id="event-search-button">Search</button><span class="result-count">${pagination.total || 0} events</span></div><div class="table-scroll"><table><thead><tr><th>Time</th><th>Event ID</th><th>Source / vendor</th><th>Category / action</th><th>Network</th><th>Parser</th><th>Status</th></tr></thead><tbody>${state.events?.length ? state.events.map(event => `<tr class="clickable" data-event-id="${escapeHtml(event.event_id)}"><td class="muted">${escapeHtml(formatDate(event.raw_ref?.ingested_at))}</td><td><code>${escapeHtml((event.event_id || '').slice(0, 14))}</code></td><td><strong>${escapeHtml(event.source?.device_type || 'Unknown')}</strong><small>${escapeHtml(event.source?.vendor || '-')} / ${escapeHtml(event.source?.product || '-')}</small></td><td>${escapeHtml(event.event?.category || 'other')}<small>${escapeHtml(event.event?.action || 'unclassified')}</small></td><td><code>${escapeHtml(event.network?.source_ip || '-')}</code><small>→ ${escapeHtml(event.network?.destination_ip || '-')}</small></td><td>${escapeHtml(event.trace?.parser_name || 'none')}</td><td>${badge(event.processing?.status || 'UNKNOWN', statusClass(event.processing?.status))}</td></tr>`).join('') : '<tr><td colspan="7" class="empty-cell">No matching events.</td></tr>'}</tbody></table></div><div class="pagination"><button class="button secondary" id="events-prev" ${pagination.has_previous ? '' : 'disabled'}>← Previous</button><span>Page ${pagination.page} of ${pagination.total_pages}</span><button class="button secondary" id="events-next" ${pagination.has_next ? '' : 'disabled'}>Next →</button></div></section>`; }
function bindEvents() { document.querySelector('#event-search-button')?.addEventListener('click', () => loadEvents(1)); document.querySelector('#event-search')?.addEventListener('keydown', event => { if (event.key === 'Enter') loadEvents(1); }); document.querySelector('#events-prev')?.addEventListener('click', () => loadEvents((state.eventPage?.page || 1) - 1)); document.querySelector('#events-next')?.addEventListener('click', () => loadEvents((state.eventPage?.page || 1) + 1)); document.querySelectorAll('[data-event-id]').forEach(row => row.addEventListener('click', () => { location.hash = `#event/${encodeURIComponent(row.dataset.eventId)}`; })); }
async function loadEvents(page) { state.eventQuery = { ...state.eventQuery, page, search: document.querySelector('#event-search')?.value.trim() || '' }; try { const result = await api.events(state.eventQuery); state.events = result.events; state.eventPage = result.pagination; render(); } catch (error) { toast(error.message, 'danger'); } }

function eventDetailPage(id) { const event = state.events.find(item => item.event_id === id); if (!event) return `<div class="empty-state large">Event is not in the current page.<small>Return to the explorer and open an event from the current result set.</small><a href="#events" class="button secondary">Back to explorer</a></div>`; const fields = [['Category', 'event.category'], ['Type', 'event.type'], ['Action', 'event.action'], ['Outcome', 'event.outcome'], ['Severity', 'event.severity'], ['Source IP', 'network.source_ip'], ['Source port', 'network.source_port'], ['Destination IP', 'network.destination_ip'], ['Destination port', 'network.destination_port'], ['Protocol', 'network.protocol']]; return `<div class="detail-header"><div><span class="eyebrow">Lossless event record</span><h2>${escapeHtml(event.event?.action || 'Event detail')}</h2><p class="mono">${escapeHtml(event.event_id)}</p></div><div class="detail-actions">${badge(event.processing?.status || 'UNKNOWN', statusClass(event.processing?.status))}<button class="button secondary" id="replay-event">Replay raw event</button><a class="button secondary" href="#events">Back</a></div></div><div class="detail-meta">${[['Source', event.source?.name], ['Vendor', event.source?.vendor], ['Product', event.source?.product], ['Parser', event.trace?.parser_name], ['Parser version', event.trace?.parser_version], ['Schema', event.schema?.version || event.trace?.schema_version], ['Ingested', formatDate(event.raw_ref?.ingested_at)]].map(([label, value]) => `<div><span>${label}</span><strong>${escapeHtml(value || '-')}</strong></div>`).join('')}</div><div class="detail-layout"><section class="surface"><div class="surface-header"><div><span class="eyebrow">Normalized output</span><h3>Universal event fields</h3></div><button class="button small secondary" id="copy-event">Copy JSON</button></div><div class="field-groups"><div><h4>EVENT</h4>${fields.slice(0, 5).map(([label, path]) => field(label, valueAt(event, path))).join('')}</div><div><h4>NETWORK</h4>${fields.slice(5).map(([label, path]) => field(label, valueAt(event, path))).join('')}</div></div><details class="json-details"><summary>Structured JSON view</summary><pre>${escapeHtml(JSON.stringify(event, null, 2))}</pre></details></section><section class="surface"><div class="surface-header"><div><span class="eyebrow">Source of truth</span><h3>Raw event</h3></div></div><div id="trace-content" class="loading-state">Loading raw content and lineage…</div></section></div>`; }
function field(label, value) { return `<div class="field"><span>${escapeHtml(label)}</span><strong class="${typeof value === 'number' || label.includes('IP') || label.includes('port') ? 'mono' : ''}">${escapeHtml(value ?? '-')}</strong></div>`; }
async function bindEventDetail() { const id = decodeURIComponent(state.page.slice(6)); let event = state.events.find(item => item.event_id === id); if (!event) { try { event = await api.event(id); state.events = [event, ...state.events]; renderPage(); return; } catch (error) { const target = document.querySelector('#content'); if (target) target.innerHTML = errorState(error.message); return; } } document.querySelector('#copy-event')?.addEventListener('click', () => navigator.clipboard?.writeText(JSON.stringify(event, null, 2)).then(() => toast('Normalized event copied', 'success'))); document.querySelector('#replay-event')?.addEventListener('click', async () => { try { await api.replay(id); toast('Raw event replayed through the pipeline', 'success'); } catch (error) { toast(error.message, 'danger'); } }); try { const trace = await api.trace(id); document.querySelector('#trace-content').innerHTML = `<div class="raw-meta">${[['Raw event ID', trace.raw_event_id], ['Hash', trace.raw_hash], ['Transport', trace.transport || event.raw_ref?.transport || '-'], ['Ingested', formatDate(trace.ingested_at || event.raw_ref?.ingested_at)]].map(([label, value]) => `<div><span>${label}</span><code>${escapeHtml(value)}</code></div>`).join('')}</div><pre class="raw-view">${escapeHtml(trace.raw_content || '(raw content unavailable)')}</pre><h4>Field lineage</h4><pre>${escapeHtml(JSON.stringify(trace.field_lineage || {}, null, 2))}</pre>`; } catch (error) { document.querySelector('#trace-content').innerHTML = errorState(error.message); } }

function pipelinePage() { const counters = state.metrics?.counters || {}; const stages = [['Collectors', 'Healthy', state.metrics?.events_per_second || 0, 'UDP + HTTP ingestion'], ['Raw preservation', 'Healthy', counters.eventsReceived || 0, 'lossless local store'], ['Queue / workers', 'Operational', counters.eventsProcessed || 0, 'local durable processing'], ['Parser / normalizer', 'Operational', counters.eventsProcessed || 0, 'universal schema v1'], ['Validation', counters.eventsFailed ? 'Review' : 'Healthy', counters.eventsFailed || 0, 'failed or dead-lettered'], ['Outputs', 'Ready', state.events.length, 'CEF / JSONL / flat JSONL']]; return `<div class="page-intro compact"><div><span class="eyebrow">Engineering operations</span><h2>Pipeline health</h2><p>Evidence from the current backend metrics and persisted stores. Queue-depth, worker-utilization, and delivery acknowledgements require additional backend telemetry.</p></div></div><section class="pipeline-grid">${stages.map(([name, status, value, note], index) => `<article class="stage-card"><span class="stage-index">${String(index + 1).padStart(2, '0')}</span><div><h3>${name}</h3><p>${note}</p></div>${badge(status, statusClass(status === 'Healthy' || status === 'Operational' || status === 'Ready' ? 'PROCESSED' : 'PARSER_ERROR'))}<strong>${value}</strong></article>`).join('')}</section><section class="surface dependency-panel"><span class="eyebrow">Telemetry coverage</span><h3>Operational signals not yet exposed by the backend</h3><div class="dependency-list"><span>Queue depth</span><span>Consumer lag</span><span>Worker utilization</span><span>p95 latency</span><span>Output acknowledgements</span></div><p>These are intentionally shown as dependencies rather than synthetic values. Add metrics endpoints before presenting them as production evidence.</p></section>`; }

function sourcesPage() { return `<div class="page-intro compact"><div><span class="eyebrow">Perimeter inventory</span><h2>Source registry</h2><p>Register firewalls, IDS, VPN gateways, proxies, and other security infrastructure with the context needed for parsing.</p></div><button class="button primary" id="show-source-form">Register source</button></div><div class="source-layout"><section class="surface"><div class="surface-header"><div><span class="eyebrow">Connected inventory</span><h3>${state.sources.length} registered sources</h3></div></div><div class="table-scroll"><table><thead><tr><th>Source</th><th>Vendor / product</th><th>Device type</th><th>Address</th><th>Status</th></tr></thead><tbody>${state.sources.length ? state.sources.map(source => `<tr><td><strong>${escapeHtml(source.name)}</strong><small>${escapeHtml(source.transport || 'unspecified')}</small></td><td>${escapeHtml(source.vendor)}<small>${escapeHtml(source.product || '-')}</small></td><td>${badge(source.device_type || 'unknown', 'info')}</td><td><code>${escapeHtml(source.device_ip || source.hostname || '-')}</code></td><td>${badge(source.active ? 'ACTIVE' : 'INACTIVE', source.active ? 'success' : 'neutral')}</td></tr>`).join('') : '<tr><td colspan="5" class="empty-cell">No sources registered.</td></tr>'}</tbody></table></div></section><section class="surface form-surface" id="source-form-panel"><div class="surface-header"><div><span class="eyebrow">Onboarding / identity</span><h3>Add a source</h3></div></div><form id="source-form"><label>Name<input name="name" required placeholder="Firewall HQ 01"></label><label>Vendor<input name="vendor" required placeholder="Fortinet"></label><label>Product<input name="product" placeholder="FortiGate 60E"></label><label>IP or hostname<input name="device_ip" placeholder="10.0.0.1"></label><label>Device type<select name="device_type"><option>firewall</option><option>ids</option><option>vpn</option><option>proxy</option><option>router</option><option>switch</option></select></label><button class="button primary" type="submit">Register source</button></form></section></div>`; }
function bindSources() { document.querySelector('#source-form')?.addEventListener('submit', async event => { event.preventDefault(); try { await api.registerSource(Object.fromEntries(new FormData(event.currentTarget))); await refresh(); toast('Source registered', 'success'); } catch (error) { toast(error.message, 'danger'); } }); document.querySelector('#show-source-form')?.addEventListener('click', () => document.querySelector('#source-form-panel')?.scrollIntoView({ behavior: 'smooth' })); }

function parsersPage() { return `<div class="page-intro compact"><div><span class="eyebrow">Plug-and-play processing</span><h2>Parser registry</h2><p>Parser definitions identify vendor formats, map fields into the universal schema, and preserve unmapped extensions.</p></div><div class="button-row"><button class="button secondary" id="reload-parsers">Reload definitions</button><a class="button primary" href="#test">Test a parser</a></div></div><div class="parser-layout"><section class="surface"><div class="surface-header"><div><span class="eyebrow">Installed definitions</span><h3>${state.parsers.length} active definitions</h3></div></div><div class="parser-list">${state.parsers.map(parser => `<article class="parser-row"><span class="parser-icon">{ }</span><div><strong>${escapeHtml(parser.name)}</strong><small>${escapeHtml(parser.vendor || 'Generic')} · ${escapeHtml(parser.format || 'auto')} · v${escapeHtml(parser.version || '1.0')}</small></div><span>${Object.keys(parser.field_mappings || {}).length} mapped fields</span>${badge('LOADED', 'success')}</article>`).join('')}</div></section><section class="surface form-surface"><div class="surface-header"><div><span class="eyebrow">Definition preview</span><h3>Register parser</h3></div></div><form id="parser-form"><label>Name<input name="name" required placeholder="vendor-firewall-v1"></label><label>Vendor<input name="vendor" required placeholder="Acme Security"></label><label>Product<input name="product" placeholder="Acme Firewall"></label><label>Format<select name="format"><option>key-value</option><option>json</option><option>regex</option></select></label><label>Match text<input name="match" placeholder="optional fingerprint"></label><label>Field mappings (JSON)<textarea name="field_mappings">{
  "src_ip": "network.source_ip",
  "action": "event.action"
}</textarea></label><button class="button primary" type="submit">Activate parser</button></form></section></div>`; }
function bindParsers() { document.querySelector('#reload-parsers')?.addEventListener('click', async () => { try { await api.reloadParsers(); await refresh(); toast('Parser definitions reloaded', 'success'); } catch (error) { toast(error.message, 'danger'); } }); document.querySelector('#parser-form')?.addEventListener('submit', async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const mappings = JSON.parse(form.get('field_mappings')); await api.registerParser({ name: form.get('name').trim(), vendor: form.get('vendor').trim(), product: form.get('product').trim(), device_type: 'security-device', format: form.get('format'), version: '1.0', extraction: { type: form.get('format') }, match_criteria: form.get('match') ? { contains: [form.get('match').trim()] } : {}, field_mappings: mappings }); await refresh(); toast('Parser activated without changing core processing code', 'success'); } catch (error) { toast(error.message.includes('JSON') ? 'Field mappings must be valid JSON' : error.message, 'danger'); } }); }

function testPage() { return `<div class="page-intro compact"><div><span class="eyebrow">Evidence lab</span><h2>Parser test bench</h2><p>Run a parser-only check or send one record through ingestion. The backend owns detection, parsing, normalization, validation, and persistence.</p></div></div><div class="test-layout"><section class="surface form-surface"><div class="surface-header"><div><span class="eyebrow">Input</span><h3>Provide a security log</h3></div></div><form id="test-form"><label>Raw log<textarea name="log">${sampleLog}</textarea></label><label>Parser selection<select name="parser_name"><option value="">Automatic matching</option>${state.parsers.map(parser => `<option value="${escapeHtml(parser.name)}">${escapeHtml(parser.name)}</option>`).join('')}</select></label><div class="button-row"><button class="button primary" name="mode" value="ingest">Ingest and normalize</button><button class="button secondary" name="mode" value="test">Test parser only</button></div></form></section><section class="surface result-surface"><div class="surface-header"><div><span class="eyebrow">Backend response</span><h3>${state.testResult ? 'Test result' : 'Waiting for a test'}</h3></div></div>${state.testResult ? `<pre>${escapeHtml(JSON.stringify(state.testResult, null, 2))}</pre>` : '<div class="empty-state">Submit a record to inspect format detection, parsed fields, normalization, validation, and traceability.</div>'}</section></div>`; }
function bindTest() { document.querySelector('#test-form')?.addEventListener('submit', async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const value = { log: form.get('log'), parser_name: form.get('parser_name') || undefined }; try { state.testResult = event.submitter.value === 'test' ? await api.testParser(value) : await api.ingest({ ...value, transport: 'local-test' }); render(); toast(event.submitter.value === 'test' ? 'Parser test completed' : 'Event ingested and normalized', 'success'); } catch (error) { toast(error.message, 'danger'); } }); }

function replayPage() { return `<div class="page-intro compact"><div><span class="eyebrow">Recovery operations</span><h2>Replay center</h2><p>Replay a persisted raw event through the current parser path. Raw records are never overwritten.</p></div></div><section class="surface"><div class="surface-header"><div><span class="eyebrow">Quarantine candidates</span><h3>Dead-letter events available for diagnosis</h3></div><a href="#dead-letter">Open quarantine →</a></div>${state.deadLetters.length ? `<div class="replay-list">${state.deadLetters.map(item => `<div class="replay-row"><div><code>${escapeHtml(item.raw_event_id)}</code><small>${escapeHtml(item.error_code || 'ERROR')} · ${escapeHtml(item.error_message || '')}</small></div><button class="button secondary replay-one" data-id="${escapeHtml(item.raw_event_id)}">Replay</button></div>`).join('')}</div>` : emptyState('No dead-letter events are currently available.')}</section>`; }
function bindReplay() { document.querySelectorAll('.replay-one').forEach(button => button.addEventListener('click', async () => { try { await api.replay(button.dataset.id); toast('Raw event replayed', 'success'); } catch (error) { toast(error.message, 'danger'); } })); }
function deadLetterPage() { return `<div class="page-intro compact"><div><span class="eyebrow">Never dropped</span><h2>Quarantine</h2><p>Unsupported, unparseable, and validation-failed inputs remain available for diagnosis and replay.</p></div>${badge(`${state.deadLetters.length} visible`, state.deadLetters.length ? 'warning' : 'success')}</div><section class="surface"><div class="table-scroll"><table><thead><tr><th>Raw event ID</th><th>Format</th><th>Error</th><th>Message</th><th>Recorded</th></tr></thead><tbody>${state.deadLetters.length ? state.deadLetters.map(item => `<tr><td><code>${escapeHtml(item.raw_event_id)}</code></td><td>${badge(item.detected_format || 'unknown', 'info')}</td><td>${badge(item.error_code || 'ERROR', 'danger')}</td><td>${escapeHtml(item.error_message)}</td><td class="muted">${escapeHtml(formatDate(item.ingested_at))}</td></tr>`).join('') : '<tr><td colspan="5" class="empty-cell">No dead-lettered events. All received logs have a route.</td></tr>'}</tbody></table></div></section>`; }

function outputsPage() { const latest = state.events[0]; return `<div class="page-intro compact"><div><span class="eyebrow">Delivery surfaces</span><h2>Output delivery</h2><p>Export the normalized event store to downstream systems using the formats currently implemented by the backend.</p></div></div><div class="output-grid">${[['CEF', 'Common Event Format', 'ArcSight-compatible SIEM lines', '/api/v1/output/cef'], ['JSONL', 'Universal JSON Lines', 'Full normalized records with traceability', '/api/v1/output/jsonl'], ['FLAT', 'Flat ML JSONL', 'Compact records for data pipelines', '/api/v1/output/flat']].map(([short, title, note, href]) => `<section class="surface output-card"><span class="output-icon">${short}</span><div><h3>${title}</h3><p>${note}</p></div><a class="button secondary" href="${href}" download>Download</a></section>`).join('')}</div><section class="surface preview-surface"><div class="surface-header"><div><span class="eyebrow">Delivery preview</span><h3>${latest ? 'Most recent event / CEF' : 'No event available'}</h3></div>${latest ? '<button class="button secondary" id="preview-output">Preview exact line</button>' : ''}</div><pre id="output-preview">${latest ? 'Select preview to request the backend-formatted output.' : 'Ingest an event before previewing output.'}</pre></section>`; }
function bindOutputs() { document.querySelector('#preview-output')?.addEventListener('click', async () => { try { const result = await api.outputPreview(state.events[0].event_id); document.querySelector('#output-preview').textContent = result.cef || 'No output returned.'; } catch (error) { document.querySelector('#output-preview').textContent = error.message; } }); }

function analyticsPage() { const counters = state.metrics?.counters || {}; return `<div class="page-intro compact"><div><span class="eyebrow">Evidence-based analytics</span><h2>Analytics</h2><p>Deterministic distributions from backend metrics are available today. Risk, anomaly, correlation, and ATT&CK views require analytical APIs before they can be shown as facts.</p></div></div><div class="analytics-grid"><section class="surface"><div class="surface-header"><div><span class="eyebrow">Outcome activity</span><h3>Processing results</h3></div></div>${distribution({ Processed: counters.eventsProcessed || 0, Partial: counters.eventsPartial || 0, Failed: counters.eventsFailed || 0, Unsupported: counters.eventsUnsupported || 0 })}</section><section class="surface"><div class="surface-header"><div><span class="eyebrow">Source activity</span><h3>Vendor distribution</h3></div></div>${distribution(state.metrics?.source_counts)}</section><section class="surface dependency-panel"><span class="eyebrow">Backend dependency</span><h3>Context-aware risk and threat hunting</h3><p>There is currently no risk-score, anomaly, correlation, ATT&CK, schema-drift, or aggregated time-series endpoint in the backend. This panel stays explicit instead of presenting fabricated security conclusions.</p><div class="dependency-list"><span>Rule-based risk</span><span>ML anomaly score</span><span>Correlation</span><span>ATT&CK evidence</span><span>Schema drift</span></div></section></div>`; }
function diagnosticsPage() { const checks = [['API health', state.health?.status || 'UNKNOWN', state.health ? `Uptime ${state.health.uptime_seconds}s` : 'No response'], ['Raw event store', 'AVAILABLE', 'Local durable storage'], ['Normalized store', state.metrics ? 'AVAILABLE' : 'UNKNOWN', `${state.metrics?.counters?.eventsProcessed || 0} processed`], ['Parser registry', state.parsers.length ? 'AVAILABLE' : 'EMPTY', `${state.parsers.length} definitions loaded`], ['Quarantine', state.deadLetters.length ? 'REVIEW' : 'CLEAR', `${state.deadLetters.length} visible records`], ['Output adapters', 'AVAILABLE', 'CEF / JSONL / flat JSONL']]; return `<div class="page-intro compact"><div><span class="eyebrow">Production diagnostics</span><h2>Diagnostics</h2><p>A compact operational readout of the services and stores that the current API can verify.</p></div></div><section class="diagnostic-grid">${checks.map(([name, status, note]) => `<article class="diagnostic-card"><span class="diagnostic-icon">●</span><div><h3>${name}</h3><p>${note}</p></div>${badge(status, statusClass(status === 'AVAILABLE' || status === 'UP' || status === 'CLEAR' ? 'PROCESSED' : status === 'REVIEW' ? 'PARTIALLY_PROCESSED' : 'UNSUPPORTED'))}</article>`).join('')}</section><section class="surface dependency-panel"><span class="eyebrow">Observability boundary</span><h3>Additional production checks need backend telemetry</h3><p>Queue backlog, worker utilization, search health, SIEM acknowledgement, Data Lake lag, and system-log filtering are not represented by current endpoints.</p></section>`; }
function emptyState(message) { return `<div class="empty-state">${escapeHtml(message)}</div>`; }
function errorState(message) { return `<div class="error-state"><strong>ULPF API unavailable</strong><span>${escapeHtml(message)}</span></div>`; }
function toast(message, tone) { const node = document.createElement('div'); node.className = `toast ${tone}`; node.textContent = message; document.querySelector('#toast')?.append(node); setTimeout(() => node.remove(), 3500); }

window.addEventListener('hashchange', () => { state.page = location.hash.slice(1) || 'overview'; render(); });
render();
refresh();
setInterval(() => refresh(), 15000);
